### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by ivan4th**
This includes deployment information

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/5)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[criproxy.dot, line 3 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/5#-Kzi8qHTAVP4hDDH-Nt9:-Kzi8qHTAVP4hDDH-NtA:bsoxbzx) ([raw file](https://github.com/mirantis/criproxy/blob/b23346efd510af56c6f190a95999e438788fd348/criproxy.dot#L3)):*
> ```
> digraph criproxy {
>         criproxy [label="CRI Proxy\nServer"];
>         dockershim [label="dockershim"];       
> ```

Whitespaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/5)*

**Comment by ivan4th** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[criproxy.dot, line 3 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/5#-Kzi8qHTAVP4hDDH-Nt9:-KziAJMEzQeBvpKxN6xe:b-896fix) ([raw file](https://github.com/mirantis/criproxy/blob/b23346efd510af56c6f190a95999e438788fd348/criproxy.dot#L3)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Whitespaces.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/5)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/5#-:-KziAOt60C3KAGDUB_8T:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/5#-:-KziW2AAYlvfWsjuUu_n:bnfp4nl)*

**Pull request merged**
