### PR TITLE
Use older version of CRI-O for deployment test

### PR DESCRIPTION
**Pull request by ivan4th**
Build CRI-O from source (v1.8.4 tag) because the current
packages no longer work with k8s 1.8.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/11)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Dockerfile, line 92 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/11#-L1HYqb6ACZet_WT5jsZ:-L1HYqb7Ip4dipRvrqbM:b-r9rj62) ([raw file](https://github.com/mirantis/criproxy/blob/2d373e343a0e264cb6bbcfb618fa8b11f7754e68/Dockerfile#L92)):*
> ```Dockerfile
> # plugin wasn't able to properly setup the net ns.
> # The bridge is based on the same commit as the one above.
> #ENV CNI_COMMIT 6bfe036c38c8e1410f1acaa4b2ee16f1851472e4
> ```

That looks like commented code.

---

*[Dockerfile, line 128 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/11#-L1HYwxq316GQNDZilGK:-L1HYwxq316GQNDZilGL:b-q7esyp) ([raw file](https://github.com/mirantis/criproxy/blob/2d373e343a0e264cb6bbcfb618fa8b11f7754e68/Dockerfile#L128)):*
> ```Dockerfile
> FROM golang:1.8
> 
> # The following based on https://github.com/kubernetes/release/blob/master/debian/Dockerfile
> ```

The following is based?

---

*[test/test-local.sh, line 27 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/11#-L1H_icmDA7p8mx9lGw5:-L1H_icmDA7p8mx9lGw6:buhon9n) ([raw file](https://github.com/mirantis/criproxy/blob/2d373e343a0e264cb6bbcfb618fa8b11f7754e68/test/test-local.sh#L27)):*
> ```Shell
> (cd "${SCRIPT_DIR}/.." && ./build-package.sh)
> 
> # SKIP_SNAPSHOT=1 CRIPROXY_DEB=/go/src/github.com/Mirantis/criproxy-nodeps_0.9.3-2_amd64.deb test/deployment-test.sh
> ```

Commented code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/11)*

**Comment by ivan4th** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Dockerfile, line 92 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/11#-L1HYqb6ACZet_WT5jsZ:-L1Me4kgkJAE32yadA4k:bym4rsv) ([raw file](https://github.com/mirantis/criproxy/blob/2d373e343a0e264cb6bbcfb618fa8b11f7754e68/Dockerfile#L92)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

That looks like commented code.
</blockquote></details>

I had to copy this part from cri-o's Dockerfile. It would be better to keep the modifications to the minimum to make it easier to update this in future if/when we have to.

---

*[Dockerfile, line 128 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/11#-L1HYwxq316GQNDZilGK:-L1MeO0EkAHUqanWlA6K:b-896fix) ([raw file](https://github.com/mirantis/criproxy/blob/2d373e343a0e264cb6bbcfb618fa8b11f7754e68/Dockerfile#L128)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

The following is based?
</blockquote></details>

Done.

---

*[test/test-local.sh, line 27 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/11#-L1H_icmDA7p8mx9lGw5:-L1MePA6kjd8dq7nOKd0:bo65gt9) ([raw file](https://github.com/mirantis/criproxy/blob/2d373e343a0e264cb6bbcfb618fa8b11f7754e68/test/test-local.sh#L27)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Commented code?
</blockquote></details>

Oops, sorry, added a file that was not intended to be included in the commit. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/11)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/11#-:-L1MghyfwVEI7I1abRlW:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 6 of 8 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/11#-:-L1N92DfWaA2f1M-FmE2:bnfp4nl)*

**Pull request merged**
