### PR TITLE
Fix lockup / crash after reconnecting to a runtime

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/6)

### CODE REVIEW

**Comment by ivan4th** [comment]
Marking as [WiP] till I verify that it helps

**Comment by ivan4th** [comment]
Reconnection appears to be fixed by this patch, removing [WiP].

**Comment by ivan4th** [comment]
Crash report by @lukaszo 
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                             
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x77d8e7]
                                                                                                                                                    
goroutine 52976 [running]: 
github.com/Mirantis/criproxy/vendor/google.golang.org/grpc.(*ClientConn).Close(0x0, 0xc4202a89c0, 0xa8b658)                                         
        /go/src/github.com/Mirantis/criproxy/vendor/google.golang.org/grpc/clientconn.go:829 +0x37
github.com/Mirantis/criproxy/pkg/proxy.(*apiClient).connectNonLocked.func1.1(0xc42007a330, 0x0)                                                     
        /go/src/github.com/Mirantis/criproxy/pkg/proxy/apiclient.go:101 +0x2aa
github.com/Mirantis/criproxy/pkg/utils.WaitForSocket(0x7ffeed460226, 0x18, 0xffffffffffffffff, 0xc4201fef58, 0x1, 0x1)                              
        /go/src/github.com/Mirantis/criproxy/pkg/utils/utils.go:53 +0x40f
github.com/Mirantis/criproxy/pkg/proxy.(*apiClient).connectNonLocked.func1(0xc42008d9d0)                                                            
        /go/src/github.com/Mirantis/criproxy/pkg/proxy/apiclient.go:106 +0x12a
created by github.com/Mirantis/criproxy/pkg/proxy.(*apiClient).connectNonLocked                                                                     
        /go/src/github.com/Mirantis/criproxy/pkg/proxy/apiclient.go:124 +0xdf```

This was caused by race condition while accessing `c.conn` in `apiclient`.

**Comment by jellonek** [comment]
:lgtm: from looking on code, but didn't tested that on any env.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/6#-:-L-bPWCW-Qd3O-WMbQC2:bvthrmt)*

**Comment by pigmej** [comment]
@ivan4th it's for code with this patch?

**Comment by ivan4th** [comment]
@pigmej it's for code after just 1 commit from this PR. The PR includes another commit which fixes this crash, too.

**Comment by pigmej** [comment]
@ivan4th it's for code with this patch?

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/6#-:-L-eXxDDwbT7Lrykfa7m:bnfp4nl)*

**Pull request merged**
