### PR TITLE
Add deployment test based on CRI-O

### PR DESCRIPTION
**Pull request by ivan4th**
It turned out that getting [CRI-O](http://cri-o.io/) run on [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) is super easy, so I used it to test criproxy in dual runtime mode.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/7)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[deployment-test.sh, line 94 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/7#-L05Ibevdld_IutlPHJW:-L05Ibevdld_IutlPHJX:bnrayc1) ([raw file](https://github.com/mirantis/criproxy/blob/d5c79f87f733a60e9797542d4b1cf8fcd6c1826c/deployment-test.sh#L94)):*
> ```Shell
> 
> step "Disabling scheduling on kube-node-2"
> "${kubectl}" taint nodes kube-node-2 dedicated=disable:NoSchedule
> ```

Hmmm... So why dind was started with 2 worker nodes? Can it be started with `NUM_NODES=1`?

---

*[deployment-test.sh, line 106 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/7#-L05JIVx9Z0ZEcNkh6lx:-L05JIVx9Z0ZEcNkh6ly:b-3omq93) ([raw file](https://github.com/mirantis/criproxy/blob/d5c79f87f733a60e9797542d4b1cf8fcd6c1826c/deployment-test.sh#L106)):*
> ```Shell
>         /bin/sh -c 'while true; do echo "this-is-crio-pod"; sleep 1; done' || true) |
>         grep --line-buffered -m 1 this-is-crio-pod; then
>   echo "Failed to verify bbtest-crio pod" >&2
> ```

Maybe that could be show with red color, with similar func as `step`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/7)*

**Comment by ivan4th** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[deployment-test.sh, line 94 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/7#-L05Ibevdld_IutlPHJW:-L09b59A9IGb4XYsrX44:b-896fix) ([raw file](https://github.com/mirantis/criproxy/blob/d5c79f87f733a60e9797542d4b1cf8fcd6c1826c/deployment-test.sh#L94)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Hmmm... So why dind was started with 2 worker nodes? Can it be started with `NUM_NODES=1`?
</blockquote></details>

Done.

---

*[deployment-test.sh, line 106 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/7#-L05JIVx9Z0ZEcNkh6lx:-L09b7UxHj_tfuxrwLnz:b-896fix) ([raw file](https://github.com/mirantis/criproxy/blob/d5c79f87f733a60e9797542d4b1cf8fcd6c1826c/deployment-test.sh#L106)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Maybe that could be show with red color, with similar func as `step`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/7)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/7#-:-L0AOUneWQBk32uHBWPh:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/7#-:-L0AOoDlwcUsYTmUmHq_:bnfp4nl)*

**Pull request merged**
