### PR TITLE
Support deployments on plain kubeadm installations & fix dockershim setup

### PR DESCRIPTION
**Pull request by ivan4th**
Fix k8s version checking
Fix dockershim setup
Remove dockershim hack for k-d-c with k8s 1.8

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/4)

### CODE REVIEW

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/4#-:-Kzc_Sxqqa8Qm8Fa69Zp:bnfp4nl)*

**Comment by jellonek** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[criproxy.sh, line 17 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/4#-KzcrXlfN_CI3NBVNxP8:-KzcrXlfN_CI3NBVNxP9:b-lqc3bh) ([raw file](https://github.com/mirantis/criproxy/blob/ea31060d1cf1d7516f9955c2f92328a75c221276/criproxy.sh#L17)):*
> ```Shell
>     version_str="$(/k8s/hyperkube --version)"
> fi
>     
> ```

White chars. Can be removed in same PR.

---

*[debian/criproxy.postinst, line 24 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/4#-KzcsBHxuLRbcFF0LuwO:-KzcsBHxuLRbcFF0LuwP:b45qxwd) ([raw file](https://github.com/mirantis/criproxy/blob/ea31060d1cf1d7516f9955c2f92328a75c221276/debian/criproxy.postinst#L24)):*
> ```
>         kubelet_service_file=/lib/systemd/system/kubelet.service
>         if [ ! -f ${kubelet_service_file} ]; then
>             kubelet_service_file=/lib/systemd/system/kubelet.service
> ```

You can also fix this line (and same in -nodeps).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/4)*

**Comment by ivan4th** [comment]
PR updated, please re-review.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[criproxy.sh, line 17 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/4#-KzcrXlfN_CI3NBVNxP8:-KzhwB0QtOW5dA3V2bqj:b-896fix) ([raw file](https://github.com/mirantis/criproxy/blob/ea31060d1cf1d7516f9955c2f92328a75c221276/criproxy.sh#L17)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

White chars. Can be removed in same PR.
</blockquote></details>

Done.

---

*[debian/criproxy.postinst, line 24 at r1](https://reviewable.io:443/reviews/mirantis/criproxy/4#-KzcsBHxuLRbcFF0LuwO:-KzhwE_URkvUOWXBesPN:b94a90v) ([raw file](https://github.com/mirantis/criproxy/blob/ea31060d1cf1d7516f9955c2f92328a75c221276/debian/criproxy.postinst#L24)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

You can also fix this line (and same in -nodeps).
</blockquote></details>

Fixed (see below, the lines have shifted)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/4#-:-KzhwJY5cGq4y1Jgtbg6:b1cr9uk)*

**Comment by jellonek** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[debian/criproxy.postinst, line 41 at r2](https://reviewable.io:443/reviews/mirantis/criproxy/4#-Kzhxlk0s52z7BLYGsP5:-Kzhxlk0s52z7BLYGsP6:b-tkg9we) ([raw file](https://github.com/mirantis/criproxy/blob/86fbbe57d26bdf67a471e53d9625f01270b54adf/debian/criproxy.postinst#L41)):*
> ```
> 
> # FIXME: this is temporary hack because 'hyperkube kubelet --experimental-dockershim'
> # used to be broken. The fix is included in k8s 1.8.4 and will be included in k8s 1.7.11.
> ```

"The fix will not be needed in k8s 1.8.4 or greater as in 1.7.11 or greater in 1.7 line."
With that - you will not need to update that line after 1.7.11 release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/4)*

**Comment by jellonek** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[debian/criproxy.postinst, line 46 at r2](https://reviewable.io:443/reviews/mirantis/criproxy/4#-KzhyVUYmWJraMBw_0In:-KzhyVUZ1pP00d4V7uDe:b-w8599x) ([raw file](https://github.com/mirantis/criproxy/blob/86fbbe57d26bdf67a471e53d9625f01270b54adf/debian/criproxy.postinst#L46)):*
> ```
>     if [[ -d /dind && -x /k8s/hyperkube && $(/k8s/hyperkube --version | awk '{print $2}') =~ (v[0-9]+\.[0-9]+\.[0-9]+)($|^[0-9]) ]]; then
>         k8s_version="${BASH_REMATCH[1]}"
>         if [[ $((echo "${k8s_version}"; echo v1.8.4 ) | sort -V | head -1) != v1.8.4 ]]; then
> ```

Ok. That still will require an update after release of 1.7.11. So please ignore above comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/4#-:-KzhybryU7ZkShX5mKyE:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/criproxy/4#-:-KziebxkA0C-xZgt6H8w:bnfp4nl)*

**Pull request merged**
