### PR TITLE
Add deployment test for k8s 1.10

### PR DESCRIPTION
**Pull request by ivan4th**
Switch from CRI-O from containerd for testing.
Fix issues with image digest translation and stdout/stderr problems in Attach/Request (k8s 1.8) that were causing problems with containerd.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/18)

### CODE REVIEW

**Comment by jellonek** [comment]
Reviewed 8 of 8 files at r1.
Review status: 0 of 2 LGTMs obtained

---

*[hack/deployment-test.sh, line 90 at r1](https://reviewable.io/reviews/mirantis/criproxy/18#-LFr3wDdB_ed4Q_biW0Z:-LFr3wDdB_ed4Q_biW0_:bcm8w34) ([raw file](https://github.com/mirantis/criproxy/blob/de9315beb5ad07c1e9f822f01307ab366d5b0c92/hack/deployment-test.sh#L90)):*
> ```Shell
> docker exec -i kube-node-1 tar -xvz </containerd.tar.gz
> #docker exec kube-node-1 systemctl daemon-reload
> #docker exec kube-node-1 systemctl start containerd
> ```

That looks like some leftover.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/18)*

**Comment by ivan4th** [comment]
Review status: 0 of 2 LGTMs obtained

---

*[hack/deployment-test.sh, line 90 at r1](https://reviewable.io/reviews/mirantis/criproxy/18#-LFr3wDdB_ed4Q_biW0Z:-LFrGGTVAntBMWHanLXT:b-x52gbo) ([raw file](https://github.com/mirantis/criproxy/blob/de9315beb5ad07c1e9f822f01307ab366d5b0c92/hack/deployment-test.sh#L90)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

That looks like some leftover.
</blockquote></details>

Thanks, fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/18)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: 0 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/18#-:-LFrLwr17RC_0lmV_HS4:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: 1 of 2 LGTMs obtained, and 1 stale

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/18#-:-LFrM5_Q6edFrB8A34C3:bnfp4nl)*

**Pull request merged**
