### PR TITLE
Add support for k8s 1.10

### PR DESCRIPTION
**Pull request by ivan4th**
- [X] basic 1.10 support
- [X] support 1.10 and older versions at the same time
- [x] add script for autogeneration of conversions
- [x] fix copyright boilerplate in generated files
- [x] retest with Virtlet

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/17)

### CODE REVIEW

**Comment by jellonek** [comment]
Review status: 0 of 33 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/proxy/proxy.go, line 95 at r2](https://reviewable.io/reviews/mirantis/criproxy/17#-LCbseCPCZ5OLqxXF2w4:-LCbseCPCZ5OLqxXF2w5:b6lqo2x) ([raw file](https://github.com/mirantis/criproxy/blob/10d84c610a5cae762158bedeacb03296d2d8768a/pkg/proxy/proxy.go#L95)):*
> ```Go
> }
> 
> func (r *RuntimeProxy) Match(fullMethod string) bool {
> ```

There should be docstrings for all these exported functions but... blah, we are less conservative in this project :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/17)*

**Comment by lukaszo** [comment]
It's too big to do correct review :) but :lgtm: 

---

Review status: 0 of 44 files reviewed at latest revision, 1 unresolved discussion.

---

*[Dockerfile, line 136 at r5](https://reviewable.io/reviews/mirantis/criproxy/17#-LDGgcFB65HSpxNrhH-H:-LDGgcFB65HSpxNrhH-I:b-fhhlo5) ([raw file](https://github.com/mirantis/criproxy/blob/f9261316424e63c2f8a4cbd39c32bdd1a078e23b/Dockerfile#L136)):*
> ```Dockerfile
>     go build -o /go/bin/conversion-gen ./cmd/conversion-gen
> 
> FROM golang:1.10
> ```

any reason to add it twice?

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/17#-:-LDHMDfJBhIOSi53sJy5:b-zi56a2)*

**Comment by ivan4th** [comment]
Review status: 0 of 44 files reviewed at latest revision, 2 unresolved discussions.

---

*[Dockerfile, line 136 at r5](https://reviewable.io/reviews/mirantis/criproxy/17#-LDGgcFB65HSpxNrhH-H:-LDHTYA1EHJPA9Oin5dg:b-yhqyvv) ([raw file](https://github.com/mirantis/criproxy/blob/f9261316424e63c2f8a4cbd39c32bdd1a078e23b/Dockerfile#L136)):*
<details><summary><i>Previously, lukaszo (Łukasz Oleś) wrote…</i></summary><blockquote>

any reason to add it twice?
</blockquote></details>

It's the start of the next stage in this multi-stage build. Note `COPY --from` commands below, the only stuff that gets copied into final image from the prev stages is what's mentioned there.

---

*[pkg/proxy/proxy.go, line 95 at r2](https://reviewable.io/reviews/mirantis/criproxy/17#-LCbseCPCZ5OLqxXF2w4:-LDHTnV19VUD2hFLZ3V4:b-896fix) ([raw file](https://github.com/mirantis/criproxy/blob/10d84c610a5cae762158bedeacb03296d2d8768a/pkg/proxy/proxy.go#L95)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

There should be docstrings for all these exported functions but... blah, we are less conservative in this project :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/17)*

**Comment by jellonek** [comment]
:lgtm:

---

Reviewed 40 of 51 files at r2, 4 of 4 files at r3, 18 of 24 files at r4, 9 of 10 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mirantis/criproxy/17#-:-LDHe1L39x2dJVfWSayF:bnfp4nl)*

**Pull request merged**
